### ISSUE TITLE
error on excuting code

### ISSUE THREAD

**Issue by alibahal** [ZigZag-Project/zigzag-v1#12]
hi, when I want to execute this code, I get this error :

 python3 top_module.py --arch ./inputs/architecture.yaml --map ./inputs/mapping.yaml --set ./inputs/settings.yaml --mempool ./inputs/memory_pool.yaml

ZigZag started running.
Target workload: AlexNet | Layer(s): [4]
Traceback (most recent call last):
  File "C:\Users\Ali\Downloads\zigzag-master\zigzag-master\top_module.py", line 161, in <module>
    for p in procs: p.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 121, 
in start
    self._popen = self._Popen(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 224, 
in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 327, 
in _Popen
    return Popen(process_obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\popen_spawn_win32.py", 
line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\reduction.py", line 60, in dump
TypeError: cannot pickle 'module' object
PS C:\Users\Ali\Downloads\zigzag-master\zigzag-master> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
 

do you have any idea about it?

**Comment by LY-Mei** [comment]
Hi,
It is due to that the multiprocessing package we used is only compatible with Linux systems.  Thus, current ZigZag can only run on Linux systems.
